### ISSUE TITLE
Does data augmentation help to improve performance

### ISSUE THREAD

**Issue by tianzq** [facebookresearch/Detectron#115]
To improve the segmentation performance, a lot of data augmentation operations would be adopted, such as rotation, adding noise.

I would like to know whether these data augmentation operations improve the performance?

Thanks!

**Comment by rbgirshick** [comment]
A longer-term todo item for us is to refactor the data loader so that data augmentations other than scale and flip can be easily used during training. We expect that this can make a big difference for some datasets, like Cityscapes. For now, most of our results are obtained with minimal data augmentation.

**Comment by tianzq** [comment]
I believe that would be a great difference. Also, I would like to post my results by using sophisticated data augmentation in the future.

**Comment by raviv** [comment]
@rbgirshick How do I configure scale augmentation?
