### ISSUE TITLE
Test MaskRCNN on COCO minival: Key already registered. Offending key: RoIAlign.

### ISSUE THREAD

**Issue by raninbowlalala** [facebookresearch/Detectron#124]
When I run :  
 python2 ../tools/test_net.py    --cfg ../configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml  TEST.WEIGHTS ../maskrcnn_model/End-to-End_R-101-FPN_36.4.pl  NUM_GPUS 2
I got the error like below:
Key already registered.
Offending key: RoIAlign.

I don't know the cause of the error, please help me.

**Comment by rbgirshick** [comment]
I'm unable to reproduce this. This type of error is what you see if you attempt to register two operators with the same name (key) with Caffe2. This suggests that something is messed up with your Caffe2 installation. The RoIAlign op did move early on from the detectron module to the set of core Caffe2 ops. It's possible that you are using an old compiled version of the detectron module that has the RoIAlign op in it together with a newer version of Caffe2 that also has RoIAlign in the set of core operators. Or maybe you have Caffe2 installed in more than one place and are somehow mixing and matching .so libraries between the installations.  At any rate, it seems like something specific to the history of your system since I cannot repo it on a clean install.

**Comment by raninbowlalala** [comment]
I reinstalled caffe2 and detectron, the error is gone. 
Thank you @rbgirshick
