### ISSUE TITLE
Inference Time Explaination 

### ISSUE THREAD

**Issue by beetleskin** [facebookresearch/Detectron#13]
> Inference times are often expressed as "X + Y", in which X is time taken in reasonably well-optimized GPU code and Y is time taken in unoptimized CPU code. (The CPU code time could be reduced substantially with additional engineering.)

Isn't it the other way around? X is always > Y in the [tables](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md).

**Comment by rbgirshick** [comment]
The explanation is correct; the "Y" time is indeed unoptimized CPU code. The fact that it's often so small is why it's left unoptimized :). The main point is that when considering how fast a model is, we can take the timing to be essentially just X because Y can be made much smaller with some engineering effort (e.g., the Y for masks is mostly time spent upsampling 100 predicted masks in one at a time; this could be replaced with a parallelized GPU implementation and take amount no time at all).

**Comment by beetleskin** [comment]
So, if I got this right, the _total_ inference time is always _X_ + _Y_, i.e. some parts of the inference is run on GPU, some on CPU? From the explanation I thought _X_ is inference time on the GPU and _Y_ is inference time on the _CPU_, i.e. the same algorithm on different hardware.

**Comment by rbgirshick** [comment]
I see the confusion. Yes, the total time is additive as in X plus Y.

When the `--multi-gpu-testing` flag is used with `{train,test}_net.py` inference happens on the dataset in a map-reduce way; the dataset is partitioned into `NUM_GPUS` subsets and they are processed in parallel. Inference on each individual image is always run on a single GPU.
