### ISSUE TITLE
Only objects described in terms of polygons are included in training

### ISSUE THREAD

**Issue by realwecan** [facebookresearch/Detectron#191]
Hi Detectron,

According to json_dataset.py, it seems that **all crowd objects are excluded from training**:

https://github.com/facebookresearch/Detectron/blob/1a3ae0c9bda2395e86aead85b87b82274931577f/lib/datasets/json_dataset.py#L227-L228

Therefore all objects (used in training) are described in terms of polygons, i.e., one object, one polygon. All crowd objects (i.e., one object, more than one polygons) will be ignored. Am I correct?

Thanks!

**Comment by Zoalfekar536** [comment]
C bc h.fig

**Comment by rbgirshick** [comment]
Crowd "objects" are cases where there are too many object instances to accurately annotate. E.g., imagine a sports stadium with hundreds of tiny people in the seats -- the whole mass of people will be marked as a crowd. These should be excluded from training because they are not individual object instances.
