### ISSUE TITLE
Run tools/infer_simple.py error

### ISSUE THREAD

**Issue by AutomanHan** [facebookresearch/Detectron#237]
I run 
`python2 tools/infer_simple.py \
  --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml \
  --output-dir /tmp/detectron-visualizations \ 
  --image-ext jpg \
  --wts https://s3-us-west-2.amazonaws.com/detectron/35857389/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml.01_37_22.KSeq0b5q/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl \
  demo`
And the error is 
![image](https://user-images.githubusercontent.com/24837080/37012662-c54c8514-2130-11e8-90a6-1974ec7e3f70.png)
I don't use docker, and my machine owns one GPU: 
Titan X 12Gmemory
I have changed NUM_GPUS:8 => NUM_GPUS=1
![image](https://user-images.githubusercontent.com/24837080/37012714-01f10a8a-2131-11e8-8e45-2055a0558009.png)

**Comment by AutomanHan** [comment]
I crop it again, the error is 
![image](https://user-images.githubusercontent.com/24837080/37016428-19e54cc6-2147-11e8-956d-50e78dc537cf.png)

**Comment by AutomanHan** [comment]
@zhezh I delete the file and make another path, but it doesn't work.
 My server can't connect the url of the pretrain mode. So I download R-101.pkl and R-50.pkl to my local machine. Copy them to my server machine, and change e2e_mask_rcnn_R-101-FPN_2x.yaml 
NUM_GPUS: 8 =>NUM_GPUS: 1
![image](https://user-images.githubusercontent.com/24837080/37193410-b4b95d82-23a4-11e8-94c1-e450e7f7597c.png)
I don't prepare the COCO dataset, now I am downloading it and copying to my server. I am not sure whether the dataset influences the result.

**Comment by zhezh** [comment]
@AutomanHan  Have you download the --wts pkl file manually (you can change this arg to local file, too)? I have run into something like that, it turns out that it is caused by corrupted pkl files. Nothing to do with the coco dataset.

Besides, I have already download r-101.pkl, here is the md5 checksum.
md5sum R-101.pkl 
c262408fcc4c119b9b6a177dd08b114f  R-101.pkl

**Comment by AutomanHan** [comment]
@zhezh Thanks for your help. It is caused by pkl file. The pkl file is not consistent with the model file. And I download the right pkl file. Thanks, again.

**Comment by groot-1313** [comment]
Hi, 

I am using python 3. I run the following command:
`python tools/infer_simple.py \ --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml \ --output-dir /tmp/detectron-visualizations \ --image-ext jpg \ --wts https://s3-us-west-2.amazonaws.com/detectron/35857389/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml.01_37_22.KSeq0b5q/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl \ demo`, after downloading the `pkl` file, I get the following error. 

> in assert_cache_file_is_ok
    'download.').format(url, file_path, cache_file_md5sum, ref_md5sum)
AssertionError: Target URL https://s3-us-west-2.amazonaws.com/detectron/35857389/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml.01_37_22.KSeq0b5q/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl appears to be downloaded to the local cache file /tmp/detectron-download-cache/35857389/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml.01_37_22.KSeq0b5q/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl, but the md5 hash of the local file does not match the reference (actual: 2bbd54fd4d14da3d821fb35daa45384d vs. expected: b'2bbd54fd4d14da3d821fb35daa45384d'). You may wish to delete the cached file and try again to trigger automatic download.

How do I fix this? I have tried changing the path in the .yaml file to the local downloaded file, but I get the same error.

**Comment by zhezh** [comment]
@groot-1313  As you can see from the output message: `the md5 hash of the local file does not match the reference`. It is probably caused by your unstable internet connection to the amzon cloud. 

You say you changed the path in yaml file to local, however, you should also change the url (`--wts `) in your command string to local, as well.

**Comment by groot-1313** [comment]
@zhezh , I did that. Now I am getting this error:
>File "/home/anaconda3/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by zhezh** [comment]
@groot-1313  pls paste your command string, so I can help figure out what happened.

**Comment by groot-1313** [comment]
@zhezh , I am running the following command:
`python tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_mas
k_rcnn_R-101-FPN_2x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl     demo`

It downloads the `pkl` file,  but this error is follows. I am using Python3.6

>line 88, in assert_cache_file_is_ok
    'download.').format(url, file_path, cache_file_md5sum, ref_md5sum)
AssertionError: Target URL https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl appears to be downloaded to the local cache file /tmp/detectron-download-cache/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl, but the md5 hash of the local file does not match the reference (actual: 3ae556bf3de044a56eb3ecb66fea5cda vs. expected: b'3ae556bf3de044a56eb3ecb66fea5cda'). You may wish to delete the cached file and try again to trigger automatic download.

NOTE: I deleted all the cached files and ran the above command. So, this is the error.  I believe there is some kind of encoding error taking place, because the md5 hash strings match `3ae556bf3de044a56eb3ecb66fea5cda`, but only difference is in the encoding of it.

**Comment by zhezh** [comment]
@groot-1313  It seems your pkl file is correct.
the code is based on python 2.7, you should use this specific version, or try changing the code related to the md5sum `b'3ae556bf3de044a56eb3ecb66fea5cda'`

**Comment by gadcam** [comment]
One way to solve it is to add the following line in [/lib/utils/io.py](https://github.com/facebookresearch/Detectron/blob/master/lib/utils/io.py#L77) between lines 77 & 79
```py
 cache_file_md5sum = bytes(cache_file_md5sum, 'utf-8')
```

**Comment by groot-1313** [comment]
I changed [this line](https://github.com/facebookresearch/Detectron/blob/master/lib/utils/io.py#L137) to `return (hash_obj.hexdigest()).encode('utf-8')`, and that error was resolved. But I faced a few more errors due to the usage of Python3 instead of Python2, but I was able to solve all the errors and get it working.
