### ISSUE TITLE
Install COCO API

### ISSUE THREAD

**Issue by gecong** [facebookresearch/Detectron#254]
When install COCO API, the documentation says:

    python2 setup.py install --user

Does "--user" means username? Should I run the command as 

    python2 setup.py install --"my_username"?

**Comment by ppwwyyxx** [comment]
Use "--user".

**Comment by tongmeihan1995** [comment]
how you install coco API

**Comment by gadcam** [comment]
@tongmeihan1995 See https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#other-dependencies

**Comment by EinavNamer** [comment]
I did the following:
sudo python2 setup.py install

**Comment by ir413** [comment]
@gecong: Please see the command (and comment) in the [installation instructions](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#other-dependencies)

>```
># Alternatively, if you do not have permissions or prefer
># not to install the COCO API into global site-packages
>python2 setup.py install --user
>```

You should run the command as shown in the instructions above. `--user` is a flag which when specified causes the package to be installed to the user site-packages instead of the global site-packages.
