### ISSUE TITLE
Fine-tune with custom dataset

### ISSUE THREAD

**Issue by Yuliang-Zou** [facebookresearch/Detectron#363]
Suppose I have a custom dataset which has some overlapping categories with MS-COCO. Is it possible to keep the filters of those specific categories? For example, I want to keep the filters for 'dog', 'cat', while train filters of other categories from scratch. 

Or should I just load pre-trained weights for other layers and train the last layers from scratch?

**Comment by ambigus9** [comment]
Please see this class [dummy_datasets.py](https://github.com/facebookresearch/Detectron/blob/master/lib/datasets/dummy_datasets.py) and if you want modify [infer_simple.py](https://github.com/facebookresearch/Detectron/blob/master/tools/infer_simple.py)

**Comment by Yuliang-Zou** [comment]
@ambigus9 Sorry I don't quite understand. Why `infer_simple.py` will affect training.

**Comment by ambigus9** [comment]
@Yuliang-Zou the training process will use the categories defined by you on your dataset.json saved on annotations folder (see [Setting Datasets](https://github.com/facebookresearch/Detectron/tree/master/lib/datasets/data) )  be sure that you are saving the categories that you want from COCO dataset that is because i mention the dummy_datasets.py 

On the other hand, infer_simple.py will use the dummy_datasets.py if you don't modify, in mention it because when you will do the infering process you must understand where are the classes saved.

I understand that you can to train with N number of classes, so please modify any .yaml config file that your are using changing NUM_CLASSES: N+1. Note that one is added because the class '__background__' .

Hope help you.

**Comment by Yuliang-Zou** [comment]
@ambigus9 Thanks!

**Comment by gadcam** [comment]
This issue could be closed.
