### ISSUE TITLE
Create a pkl weights file

### ISSUE THREAD

**Issue by lunix1982** [facebookresearch/Detectron#38]
Hello.
I have images whose resolution differs from the resolution in the pretrained models (pkl weight files). It seems that I need to train my own model before I can use Detectron.
How to create a pickle weights file?
From what framework I have to save a model to a file?
Thanks.

**Comment by rbgirshick** [comment]
There's no need to retrain. The inference code will resize the input image appropriately. That said, please read the "note" in this section https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md#1-directory-of-image-files.

The pkl files are saved by Detectron.

**Comment by lunix1982** [comment]
Does not this class detect only certain classes?
I need to detect my own objects and I thought I have to train a new model on my train images.

**Comment by mattdingmeng** [comment]
@rbgirshick In Caffe2, model is in .pb format. Here, pre-train models in in .pkl format. 
I am working on the C++ implementation of the inference code. However, It's may not easy to load the pre-train model (pkl format) and the yaml config file in C++. Are you going to use two .pb format files to store the models, so that it can be quickly deployed in Caffe2 c++ framework. Any suggestions for C++ implementation?
