### ISSUE TITLE
How to run test_spatial_narrow_as_op.py outside of detectron directory

### ISSUE THREAD

**Issue by adeelz92** [facebookresearch/Detectron#499]
This issue may sound stupid but I am an inexperienced user, so.

I have setup everything successfully, and when I run 'python3.6 detectron/tests/test_spatial_narrow_as_op.py' from inside the detectron directory, it runs successfully.

However, is it possible to make this global, so that I can run this from anywhere ?

Thanks

**Comment by ir413** [comment]
Hi @adeelz92, setting up python packages following the installation instruction should enable you to run detectron tools/tests from anywhere. Since detectron does not support python 3 at this time, we setup python packages for python 2. So you should probably use `python2 /path/to/tool` instead of `python3.6 /path/to/tool` when running detectron tools/tests.
