### ISSUE TITLE
How to run inference with batch > 1?

### ISSUE THREAD

**Issue by antocapp** [facebookresearch/Detectron#533]
Is there a way to run inference scripts like infer.py or infer_simple.py feeding into network more than one image? 

Thanks

**Comment by ir413** [comment]
Hi @antocapp, batched inference is not supported at this time. See #451 for a related discussion.

**Comment by beniz** [comment]
Hi, one of our very talented interns, @chichaj has worked on a (C++) version of batched inference, see https://github.com/jolibrain/deepdetect/pull/490 and https://github.com/jolibrain/deepdetect/pull/490/commits/42223ea8953f4a2b10f79f174372d7f1ee8fb75d for code-level details. 

This may help some users to replicate it in Python since other implementations do not appear to have support for batched inference either, see https://github.com/roytseng-tw/Detectron.pytorch/issues/91

**Comment by 13070151771** [comment]
high~@antocapp，sorry 2 bother U,I meet this problem too,have you solve it~~~

**Comment by yashenkoxciv** [comment]
Try to concatenate images and feed it to the network. Then, separate outputs.
