### ISSUE TITLE
Can't find blob: gpu_0/rois

### ISSUE THREAD

**Issue by PacteraKun** [facebookresearch/Detectron#558]
Hi, all. 

I want to fetch the blob 'rois' to get ground truth bounding box labels and coordinates after the network has generated the final predicated bounding boxes. And then I will generate new labels according to the IoU overlap between ground truth bounding box coordinates and predicated bounding box coordinates. Then I will add another stage of faster rcnn head to predicted new bounding boxes based these predicated bounding boxes from previous stage. 

### Actual results

I found a error happened. 
![image](https://user-images.githubusercontent.com/40010065/42666057-86e9df48-85f7-11e8-9456-f2f6bf91b5fc.png)

### Detailed steps to reproduce

After faster rcnn head and output function, I add another stage faster rcnn head and output function whose input is the predicted boxes from previous stage and their labels are assigned as the same as faster rcnn according to the maximum IoU overlap between predicated boxes and ground truth boxes. 

```
python tools/train_net.py --cfg configs/my_configs/e2e_faster_rcnn_X-101-64x4D-FPN_1X.yaml 
```

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by ir413** [comment]
Hi @PacteraKun, the error you're getting is due to the blob not being present in the workspace at the time your `FetchBlob` call is executed. Looking at the stack trace, it seems that you're trying to fetch a blob from the workspace at the network construction stage (see #374 for discussion). To implement ideas in the direction you describe, I suggest studying how joint training of RPN with Fast/Mask R-CNN (i.e. end-to-end Faster R-CNN training) is implemented (e.g. see [GenerateProposalLabels](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/detector.py#L140)).
