### ISSUE TITLE
Constant Inference time while testing on 'coco_2014_minival' 5k dataset

### ISSUE THREAD

**Issue by sidnav** [facebookresearch/Detectron#623]
On running the testing code `test_net.py` I have observed that the Inference time (X+Y) reaches a constant value irrespective of the image it is running inference on, why does this happen?

**Comment by ir413** [comment]
Hi @sidnav, predictions at test-time are computed at the scale defined by `TEST.SCALE` (capped by `TEST.MAX_SIZE`). You can find the description of the config options [here](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#coco-api-undefined-symbol-error) and the relevant function [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/blob.py#L100).

**Comment by sidnav** [comment]
Hi @ir413, sure, but how is it that when I run the `infer_simple.py`, the images in the demo folder take different amount of  inference times for the same `TEST.SCALE` paramter

**Comment by ir413** [comment]
Time logged by `test_net.py` is the average time taken per image. If it becomes constant that means that it converges to a certain value. Due to the settings I mentioned above, each image will end up being of a similar size which makes the convergence easier. Other than the image size, the number of times the task-specific heads are run per image is another factor that affects this (that too is capped per image). You are not seeing the same when running `infer_simple.py` since the number of images used to compute the average time is small.

**Comment by sidnav** [comment]
@ir413, understood, Thank you!
