### ISSUE TITLE
ImportError: No module named 'detectron'

### ISSUE THREAD

**Issue by shadowdk3** [facebookresearch/Detectron#685]
hi, 
I got error when I run "python detectron/tests/test_spatial_narrow_as_op.py"

Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 29, in <module>
    import detectron.utils.c2 as c2_utils
ImportError: No module named 'detectron'

What I did:
caffe2 installed, and check OK

git clone https://github.com/jasonbunk/Detectron.git
sudo mv Detectron /opt
cd /opt/Detectron
./python2_to_python3_conversion_automated.sh
echo "alias python=python3" >> ~/.bashrc
source ~/.bashrc
sudo -H pip install -r requirments.txt
make
python3 detectron/tests/test_spatial_narrow_as_op.py

I also set env path:
export DETECTRON=/opt/Detectron

### System information

* Operating system: ubuntu16.04
* CUDA version: 8.0
* cuDNN version: 6.0
* `PYTHONPATH` environment variable: python3

**Comment by ir413** [comment]
Hi @shadowdk3, it seems that your python modules are not getting set up correctly. Since you are not following the official detectron installation instructions, you should verify that the code after the changes made by your `python2_to_python3_conversion_automated.sh` script is still compatible with detectron's `Makefile` and `setup.py`.
