### ISSUE TITLE
Why the cfg.RPN.RPN_ON always True?

### ISSUE THREAD

**Issue by xzhewei** [facebookresearch/Detectron#779]
### Expected results

I want to use mask rcnn on COCO. I use 12_2017_baselines/e2e_mask_rcnn_R-50-C4_1x.yaml. 

### Actual results

But, in minibatch.py, I found the cfg.RPN.RPN_ON always True. The line `valid = fast_rcnn_roi_data.add_fast_rcnn_blobs(blobs, im_scales, roidb)` never execute. 

### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by ir413** [comment]
Hi @xzhewei, `RPN.RPN_ON` field is set to `True` since you're using a model with an RPN subnetwork. Please see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L669-L671) for the config option description and [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L1076-L1077) for how its value is inferred.
