### ISSUE TITLE
Extract Predictor Net?

### ISSUE THREAD

**Issue by ananth-kv** [facebookresearch/Detectron#92]
Hi, I was wondering if there's a method similar to **model_helper.ExtractPredictorNet()** for detectron.

I want to do forward pass (basically predict) during **training** for which I tried workspace.Predictor() but that doesn't seem to use gpu, correct me if I'm wrong. 

Not sure removing gradientOps a good idea coz am using the same model to train, so I cant use RunNet() again.

So, I am not sure how to forward pass the model on external data (not from the batch) during training?

Kindly help.

**Comment by rbgirshick** [comment]
Caffe2 nets are just simple data structures. You can `Clone` the forward pass network before the gradient ops are added in order to have another network that just runs the forward pass. You can also edit the ops in that net as needed. You may find this example code helpful https://gist.github.com/rbgirshick/a701aeef9954b2d2e0d50b31cbfc615c.
